// <auto-generated />
using System;
using AviationMaintenanceManagementSystem.Data_CRUDops_;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AviationMaintenanceManagementSystem.Migrations
{
    [DbContext(typeof(MaintenanceContext))]
    partial class MaintenanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25");

            modelBuilder.Entity("AviationMaintenanceManagementSystem.ModelClasses.ActualWorkOrder", b =>
                {
                    b.Property<string>("JobNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectiveAction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discrepancy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("EquipmentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobNumber");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("AviationMaintenanceManagementSystem.ModelClasses.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AviationMaintenanceManagementSystem.ModelClasses.Inventory", b =>
                {
                    b.Property<string>("PartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedJobNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedWorkCenter")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Nomenclature")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecievedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PartNumber");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("AviationMaintenanceManagementSystem.ModelClasses.WorkCenter", b =>
                {
                    b.Property<int>("WorkCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneExtension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("WorkCenterId");

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("AviationMaintenanceManagementSystem.ModelClasses.ActualWorkOrder", b =>
                {
                    b.HasOne("AviationMaintenanceManagementSystem.ModelClasses.WorkCenter", "WorkCenter")
                        .WithMany("ActualWorkOrders")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
